services:
  flex-dummy-database:
    image: postgres:14-alpine
    command: postgres -c "log_lock_waits=on" -N 1000 -c "fsync=off"
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_DB: ${DB_NAME}
    healthcheck:
      test: "pg_isready --username=${DB_USER} --dbname=${DB_NAME}"
      timeout: 10s
      retries: 20
    ports:
      - ${DB_PORT}:5432
    volumes:
      - demo-database_data:/var/lib/postgresql/data

volumes:
  demo-database_data:
