default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  host: localhost
  port: 5432
  username: <%= ENV.fetch("DATABASE_USER") { ENV["CI"].present? ? "postgres" : (ENV["USER"] || "postgres") } %>
  password: <%= ENV.fetch("DATABASE_PASSWORD") { "postgres" } %>

development:
  <<: *default
  database: flex_sdk_dummy_development

test:
  <<: *default
  database: flex_sdk_dummy_test
