name: CI

on:
  push:
    branches:
      - main
  pull_request:
    paths:
      - template/{{app_name}}/engines/flex/**
      - .github/workflows/ci.yml

defaults:
  run:
    working-directory: template/{{app_name}}/engines/flex

jobs:
  ci:
    name: ${{ matrix.make_command }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        make_command: [lint-ci, test]

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1
        with:
          working-directory: template/{{app_name}}/engines/flex

      - name: Install dependencies
        run: bundle install

      - name: Run check
        run: make ${{ matrix.make_command }}
