name: CI

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  ci:
    name: ${{ matrix.make_command }}
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        make_command: [lint-ci, test]

    steps:
      - uses: actions/checkout@v4

      - uses: ruby/setup-ruby@v1

      - name: Install dependencies
        run: make setup

      - name: Setup required env variables
        run: make .env

      - name: Setup database
        if: ${{ matrix.make_command == 'test' }}
        run: make init-db

      - name: Run ${{ matrix.make_command }}
        run: make ${{ matrix.make_command }}
